name: tinaem
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cupertino_icons: ^1.0.8
  
  persistent_bottom_nav_bar_v2: ^4.2.8
  swipe_cards: ^2.0.0+1
  dotted_border: ^2.1.0
  image_cropper: ^5.0.0
  image_picker: ^1.0.4
  
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # # Nếu cần dùng:
  # user_repository:
  #   path: packages/user_repository
  # geolocator: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/icons/
